require("dotenv").config();
const express = require("express");
const app = express();
const cors = require("cors");
const router = require("./routes/homeRouter");
app.use(express.urlencoded({ extended: false }));
app.use(cors());
app.use(express.json());
app.use("/", router);
app.listen(3000, () => console.log("app listening on port 3000!"));
